namespace :country do
  desc 'Adding countries values to Country table'
  task setup: :environment do
    chile = Country.find_by(name: 'Chile')
    if chile.present?
      puts 'Add missing attributes to Chile country'
      chile.update_attributes(flag_emoji: '🇨🇱', is_available: true)
    else
      puts 'Chile record does not exist'
    end
    countries = [
      { name: 'México', phone_prefix: '+52', flag_emoji: '🇲🇽',
        is_available: true },
      { name: 'Afganistán', phone_prefix: '+93', flag_emoji: '🇦🇫',
        is_available: false },
      { name: 'Alemania', phone_prefix: '+49', flag_emoji: '🇩🇪',
        is_available: false },
      { name: 'Albania', phone_prefix: '+355', flag_emoji: '🇦🇱',
        is_available: false },
      { name: 'Algeria', phone_prefix: '+213', flag_emoji: '🇩🇿',
        is_available: false },
      { name: 'Andorra', phone_prefix: '+376', flag_emoji: '🇦🇩',
        is_available: false },
      { name: 'Angola', phone_prefix: '+244', flag_emoji: '🇦🇴',
        is_available: false },
      { name: 'Anguila', phone_prefix: '+1264', flag_emoji: '🇦🇮',
        is_available: false },
      { name: 'Antártida', phone_prefix: '+672', flag_emoji: '🇦🇶',
        is_available: false },
      { name: 'Antigua y Barbuda', phone_prefix: '+1268', flag_emoji: '🇦🇬',
        is_available: false },
      { name: 'Argentina', phone_prefix: '+54', flag_emoji: '🇦🇷',
        is_available: false },
      { name: 'Armenia', phone_prefix: '+374', flag_emoji: '🇦🇲',
        is_available: false },
      { name: 'Aruba', phone_prefix: '+297', flag_emoji: '🇦🇼',
        is_available: false },
      { name: 'Australia', phone_prefix: '+61', flag_emoji: '🇦🇺',
        is_available: false },
      { name: 'Austria', phone_prefix: '+43', flag_emoji: '🇦🇹',
        is_available: false },
      { name: 'Azerbaiyán', phone_prefix: '+994', flag_emoji: '🇦🇿',
        is_available: false },
      { name: 'Bahamas', phone_prefix: '+1242', flag_emoji: '🇧🇸',
        is_available: false },
      { name: 'Baréin', phone_prefix: '+973', flag_emoji: '🇧🇭',
        is_available: false },
      { name: 'Bangladés', phone_prefix: '+880', flag_emoji: '🇧🇩',
        is_available: false },
      { name: 'Barbados', phone_prefix: '+1246', flag_emoji: '🇧🇧',
        is_available: false },
      { name: 'Bielorrusia', phone_prefix: '+375', flag_emoji: '🇧🇾',
        is_available: false },
      { name: 'Bélgica', phone_prefix: '+32', flag_emoji: '🇧🇪',
        is_available: false },
      { name: 'Belice', phone_prefix: '+501', flag_emoji: '🇧🇿',
        is_available: false },
      { name: 'Benín', phone_prefix: '+229', flag_emoji: '🇧🇯',
        is_available: false },
      { name: 'Bermudas', phone_prefix: '+1441', flag_emoji: '🇧🇲',
        is_available: false },
      { name: 'Bután', phone_prefix: '+975', flag_emoji: '🇧🇹',
        is_available: false },
      { name: 'Bolivia', phone_prefix: '+591', flag_emoji: '🇧🇴',
        is_available: false },
      { name: 'Caribe Neerlandés', phone_prefix: '+599', flag_emoji: '🇧🇶',
        is_available: false },
      { name: 'Bosnia Y Herzegovina', phone_prefix: '+387', flag_emoji: '🇧🇦',
        is_available: false },
      { name: 'Isla Bouvet', phone_prefix: '+47', flag_emoji: '🇧🇻',
        is_available: false },
      { name: 'Brasil', phone_prefix: '+55', flag_emoji: '🇧🇷',
        is_available: false },
      { name: 'Territorio Británico Del Océano Índico', phone_prefix: '+1284',
        flag_emoji: '🇮🇴', is_available: false },
      { name: 'Brunéi', phone_prefix: '+673', flag_emoji: '🇧🇳',
        is_available: false },
      { name: 'Bulgaria', phone_prefix: '+359', flag_emoji: '🇧🇬',
        is_available: false },
      { name: 'Burkina Faso', phone_prefix: '+226', flag_emoji: '🇧🇫',
        is_available: false },
      { name: 'Burundi', phone_prefix: '+257', flag_emoji: '🇧🇮',
        is_available: false },
      { name: 'Camboya', phone_prefix: '+855', flag_emoji: '🇰🇭',
        is_available: false },
      { name: 'Camerún', phone_prefix: '+237', flag_emoji: '🇨🇲',
        is_available: false },
      { name: 'Canadá', phone_prefix: '+1', flag_emoji: '🇨🇦',
        is_available: false },
      { name: 'Cabo Verde', phone_prefix: '+238', flag_emoji: '🇨🇻',
        is_available: false },
      { name: 'Islas Caimán', phone_prefix: '+1345', flag_emoji: '🇰🇾',
        is_available: false },
      { name: 'República Centroafricana', phone_prefix: '+236',
        flag_emoji: '🇨🇫', is_available: false },
      { name: 'Chad', phone_prefix: '+235', flag_emoji: '🇹🇩',
        is_available: false },
      { name: 'China', phone_prefix: '+86', flag_emoji: '🇨🇳',
        is_available: false },
      { name: 'Islas Cocos', phone_prefix: '+672', flag_emoji: '🇨🇨',
        is_available: false },
      { name: 'Colombia', phone_prefix: '+57', flag_emoji: '🇨🇴',
        is_available: false },
      { name: 'Comoras', phone_prefix: '+269', flag_emoji: '🇰🇲',
        is_available: false },
      { name: 'República Democrática Del Congo', phone_prefix: '+243',
        flag_emoji: '🇨🇩', is_available: false },
      { name: 'Congo', phone_prefix: '+242', flag_emoji: '🇨🇬',
        is_available: false },
      { name: 'Islas Cook', phone_prefix: '+682', flag_emoji: '🇨🇰',
        is_available: false },
      { name: 'Costa Rica', phone_prefix: '+506', flag_emoji: '🇨🇷',
        is_available: false },
      { name: 'Côte D’Ivoire', phone_prefix: '+225', flag_emoji: '🇨🇮',
        is_available: false },
      { name: 'Croacia', phone_prefix: '+385', flag_emoji: '🇭🇷',
        is_available: false },
      { name: 'Curazao', phone_prefix: '+599', flag_emoji: '🇨🇼',
        is_available: false },
      { name: 'Chequia', phone_prefix: '+420', flag_emoji: '🇨🇿',
        is_available: false },
      { name: 'Dominica', phone_prefix: '+1767', flag_emoji: '🇩🇲',
        is_available: false },
      { name: 'República Dominicana', phone_prefix: '+18', flag_emoji: '🇩🇴',
        is_available: false },
      { name: 'Timor-Leste', phone_prefix: '+670', flag_emoji: '🇹🇱',
        is_available: false },
      { name: 'Ecuador', phone_prefix: '+593', flag_emoji: '🇪🇨',
        is_available: false },
      { name: 'Egipto', phone_prefix: '+20', flag_emoji: '🇪🇬',
        is_available: false },
      { name: 'El Salvador', phone_prefix: '+503', flag_emoji: '🇸🇻',
        is_available: false },
      { name: 'Guinea Ecuatorial', phone_prefix: '+240', flag_emoji: '🇬🇶',
        is_available: false },
      { name: 'Eritrea', phone_prefix: '+291', flag_emoji: '🇪🇷',
        is_available: false },
      { name: 'Estonia', phone_prefix: '+372', flag_emoji: '🇪🇪',
        is_available: false },
      { name: 'Etiopía', phone_prefix: '+251', flag_emoji: '🇪🇹',
        is_available: false },
      { name: 'Islas Malvinas', phone_prefix: '+500', flag_emoji: '🇫🇰',
        is_available: false },
      { name: 'Islas Feroe', phone_prefix: '+298', flag_emoji: '🇫🇴',
        is_available: false },
      { name: 'Fiyi', phone_prefix: '+679', flag_emoji: '🇫🇯',
        is_available: false },
      { name: 'Finlandia', phone_prefix: '+358', flag_emoji: '🇫🇮',
        is_available: false },
      { name: 'Francia', phone_prefix: '+33', flag_emoji: '🇫🇷',
        is_available: false },
      { name: 'Guayana Francesa', phone_prefix: '+594', flag_emoji: '🇬🇫',
        is_available: false },
      { name: 'Gabón', phone_prefix: '+241', flag_emoji: '🇬🇦',
        is_available: false },
      { name: 'Gambia', phone_prefix: '+220', flag_emoji: '🇬🇲',
        is_available: false },
      { name: 'Georgia', phone_prefix: '+995', flag_emoji: '🇬🇪',
        is_available: false },
      { name: 'Ghana', phone_prefix: '+233', flag_emoji: '🇬🇭',
        is_available: false },
      { name: 'Gibraltar', phone_prefix: '+350', flag_emoji: '🇬🇮',
        is_available: false },
      { name: 'Grecia', phone_prefix: '+30', flag_emoji: '🇬🇷',
        is_available: false },
      { name: 'Groelandia', phone_prefix: '+299', flag_emoji: '🇬🇱',
        is_available: false },
      { name: 'Granada', phone_prefix: '+1473', flag_emoji: '🇬🇺',
        is_available: false },
      { name: 'Guam', phone_prefix: '+1671', flag_emoji: '🇬🇩',
        is_available: false },
      { name: 'Guadalupe', phone_prefix: '+590', flag_emoji: '🇬🇵',
        is_available: false },
      { name: 'Guatemala', phone_prefix: '+502', flag_emoji: '🇬🇹',
        is_available: false },
      { name: 'Guernsey', phone_prefix: '+44', flag_emoji: '🇬🇬',
        is_available: false },
      { name: 'Guinea', phone_prefix: '+224', flag_emoji: '🇬🇳',
        is_available: false },
      { name: 'Guinea-Bisáu', phone_prefix: '+245', flag_emoji: '🇬🇼',
        is_available: false },
      { name: 'Guyana', phone_prefix: '+592', flag_emoji: '🇬🇾',
        is_available: false },
      { name: 'Haití', phone_prefix: '+509', flag_emoji: '🇭🇹',
        is_available: false },
      { name: 'Islas Heard Y McDonald', phone_prefix: '+0', flag_emoji: '🇭🇲',
        is_available: false },
      { name: 'Vaticano', phone_prefix: '+39', flag_emoji: '🇻🇦',
        is_available: false },
      { name: 'Honduras', phone_prefix: '+504', flag_emoji: '🇭🇳',
        is_available: false },
      { name: 'Hong Kong', phone_prefix: '+852', flag_emoji: '🇭🇰',
        is_available: false },
      { name: 'Hungaria', phone_prefix: '+36', flag_emoji: '🇭🇺',
        is_available: false },
      { name: 'Islandia', phone_prefix: '+354', flag_emoji: '🇮🇸',
        is_available: false },
      { name: 'India', phone_prefix: '+91', flag_emoji: '🇮🇳',
        is_available: false },
      { name: 'Indonesia', phone_prefix: '+62', flag_emoji: '🇮🇩',
        is_available: false },
      { name: 'Irak', phone_prefix: '+964', flag_emoji: '🇮🇶',
        is_available: false },
      { name: 'Irlanda', phone_prefix: '+353', flag_emoji: '🇮🇪',
        is_available: false },
      { name: 'Isla De Man', phone_prefix: '+44', flag_emoji: '🇮🇲',
        is_available: false },
      { name: 'Israel', phone_prefix: '+972', flag_emoji: '🇮🇱',
        is_available: false },
      { name: 'Italia', phone_prefix: '+39', flag_emoji: '🇮🇹',
        is_available: false },
      { name: 'Jamaica', phone_prefix: '+1876', flag_emoji: '🇯🇲',
        is_available: false },
      { name: 'Japón', phone_prefix: '+81', flag_emoji: '🇯🇵',
        is_available: false },
      { name: 'Jersey', phone_prefix: '+44', flag_emoji: '🇯🇪',
        is_available: false },
      { name: 'Jordania', phone_prefix: '+962', flag_emoji: '🇯🇴',
        is_available: false },
      { name: 'Kazajistán', phone_prefix: '+7', flag_emoji: '🇰🇿',
        is_available: false },
      { name: 'Kenia', phone_prefix: '+254', flag_emoji: '🇰🇪',
        is_available: false },
      { name: 'Kiribati', phone_prefix: '+686', flag_emoji: '🇰🇮',
        is_available: false },
      { name: 'Corea Del Sur', phone_prefix: '+82', flag_emoji: '🇰🇷',
        is_available: false },
      { name: 'Kosovo', phone_prefix: '+383', flag_emoji: '🇽🇰',
        is_available: false },
      { name: 'Kuwait', phone_prefix: '+965', flag_emoji: '🇰🇼',
        is_available: false },
      { name: 'Kirguistán', phone_prefix: '+996', flag_emoji: '🇰🇬',
        is_available: false },
      { name: 'Laos', phone_prefix: '+856', flag_emoji: '🇱🇦',
        is_available: false },
      { name: 'Letonia', phone_prefix: '+371', flag_emoji: '🇱🇻',
        is_available: false },
      { name: 'Líbano', phone_prefix: '+961', flag_emoji: '🇱🇧',
        is_available: false },
      { name: 'Lesoto', phone_prefix: '+266', flag_emoji: '🇱🇸',
        is_available: false },
      { name: 'Liberia', phone_prefix: '+231', flag_emoji: '🇱🇷',
        is_available: false },
      { name: 'Libia', phone_prefix: '+218', flag_emoji: '🇱🇾',
        is_available: false },
      { name: 'Liechtenstein', phone_prefix: '+423', flag_emoji: '🇱🇮',
        is_available: false },
      { name: 'Lituania', phone_prefix: '+370', flag_emoji: '🇱🇹',
        is_available: false },
      { name: 'Luxemburgo', phone_prefix: '+352', flag_emoji: '🇱🇺',
        is_available: false },
      { name: 'Macao', phone_prefix: '+853', flag_emoji: '🇲🇴',
        is_available: false },
      { name: 'Macedonia', phone_prefix: '+389', flag_emoji: '🇲🇰',
        is_available: false },
      { name: 'Madagascar', phone_prefix: '+261', flag_emoji: '🇲🇬',
        is_available: false },
      { name: 'Malaui', phone_prefix: '+265', flag_emoji: '🇲🇼',
        is_available: false },
      { name: 'Malasia', phone_prefix: '+60', flag_emoji: '🇲🇾',
        is_available: false },
      { name: 'Maldivas', phone_prefix: '+960', flag_emoji: '🇲🇻',
        is_available: false },
      { name: 'Mali', phone_prefix: '+223', flag_emoji: '🇲🇱',
        is_available: false },
      { name: 'Malta', phone_prefix: '+356', flag_emoji: '🇲🇹',
        is_available: false },
      { name: 'Islas Marshall', phone_prefix: '+692', flag_emoji: '🇲🇭',
        is_available: false },
      { name: 'Martinica', phone_prefix: '+596', flag_emoji: '🇲🇶',
        is_available: false },
      { name: 'Mauritania', phone_prefix: '+222', flag_emoji: '🇲🇷',
        is_available: false },
      { name: 'Mauricio', phone_prefix: '+230', flag_emoji: '🇲🇺',
        is_available: false },
      { name: 'Mayotte', phone_prefix: '+269', flag_emoji: '🇾🇹',
        is_available: false },
      { name: 'Micronesia', phone_prefix: '+691', flag_emoji: '🇫🇲',
        is_available: false },
      { name: 'Moldavia', phone_prefix: '+373', flag_emoji: '🇲🇩',
        is_available: false },
      { name: 'Mónaco', phone_prefix: '+377', flag_emoji: '🇲🇨',
        is_available: false },
      { name: 'Mongolia', phone_prefix: '+976', flag_emoji: '🇲🇳',
        is_available: false },
      { name: 'Montenegro', phone_prefix: '+382', flag_emoji: '🇲🇪',
        is_available: false },
      { name: 'Montserrat', phone_prefix: '+1664', flag_emoji: '🇲🇸',
        is_available: false },
      { name: 'Marruecos', phone_prefix: '+212', flag_emoji: '🇲🇦',
        is_available: false },
      { name: 'Mozambique', phone_prefix: '+258', flag_emoji: '🇲🇿',
        is_available: false },
      { name: 'Namibia', phone_prefix: '+264', flag_emoji: '🇳🇦',
        is_available: false },
      { name: 'Nauru', phone_prefix: '+674', flag_emoji: '🇳🇷',
        is_available: false },
      { name: 'Nepal', phone_prefix: '+977', flag_emoji: '🇳🇵',
        is_available: false },
      { name: 'Netherlands', phone_prefix: '+31', flag_emoji: '🇳🇱',
        is_available: false },
      { name: 'Caribe Neerlandés', phone_prefix: '+599', flag_emoji: '🇧🇶',
        is_available: false },
      { name: 'Nueva Caledonia', phone_prefix: '+687', flag_emoji: '🇳🇨',
        is_available: false },
      { name: 'Nueva Zelanda', phone_prefix: '+64', flag_emoji: '🇳🇿',
        is_available: false },
      { name: 'Nicaragua', phone_prefix: '+505', flag_emoji: '🇳🇮',
        is_available: false },
      { name: 'Niger', phone_prefix: '+227', flag_emoji: '🇳🇪',
        is_available: false },
      { name: 'Nigeria', phone_prefix: '+234', flag_emoji: '🇳🇬',
        is_available: false },
      { name: 'Niue', phone_prefix: '+683', flag_emoji: '🇳🇺',
        is_available: false },
      { name: 'Isla Norfolk', phone_prefix: '+672', flag_emoji: '🇳🇫',
        is_available: false },
      { name: 'Islas Marianas', phone_prefix: '+1670', flag_emoji: '🇲🇵',
        is_available: false },
      { name: 'Noruega', phone_prefix: '+47', flag_emoji: '🇳🇴',
        is_available: false },
      { name: 'Omán', phone_prefix: '+968', flag_emoji: '🇴🇲',
        is_available: false },
      { name: 'Pakistán', phone_prefix: '+92', flag_emoji: '🇵🇰',
        is_available: false },
      { name: 'Palaos', phone_prefix: '+680', flag_emoji: '🇵🇼',
        is_available: false },
      { name: 'Panamá', phone_prefix: '+507', flag_emoji: '🇵🇦',
        is_available: false },
      { name: 'Paraguay', phone_prefix: '+595', flag_emoji: '🇵🇾',
        is_available: false },
      { name: 'Papúa Nueva Guinea', phone_prefix: '+675', flag_emoji: '🇵🇬',
        is_available: false },
      { name: 'Perú', phone_prefix: '+51', flag_emoji: '🇵🇪',
        is_available: false },
      { name: 'Filipinas', phone_prefix: '+63', flag_emoji: '🇵🇭',
        is_available: false },
      { name: 'Islas Pitcairn', phone_prefix: '+870', flag_emoji: '🇵🇳',
        is_available: false },
      { name: 'Polonia', phone_prefix: '+48', flag_emoji: '🇵🇱',
        is_available: false },
      { name: 'Portugal', phone_prefix: '+351', flag_emoji: '🇵🇹',
        is_available: false },
      { name: 'Puerto Rico', phone_prefix: '+1787', flag_emoji: '🇵🇷',
        is_available: false },
      { name: 'Catar', phone_prefix: '+974', flag_emoji: '🇶🇦',
        is_available: false },
      { name: 'Reunión', phone_prefix: '+262', flag_emoji: '🇷🇪',
        is_available: false },
      { name: 'Rumania', phone_prefix: '+40', flag_emoji: '🇷🇴',
        is_available: false },
      { name: 'Rusia', phone_prefix: '+7', flag_emoji: '🇷🇺',
        is_available: false },
      { name: 'Ruanda', phone_prefix: '+250', flag_emoji: '🇷🇼',
        is_available: false },
      { name: 'San Bartolomé', phone_prefix: '+590', flag_emoji: '🇧🇱',
        is_available: false },
      { name: 'Santa Elena', phone_prefix: '+290', flag_emoji: '🇸🇭',
        is_available: false },
      { name: 'Santa Lucía', phone_prefix: '+1758', flag_emoji: '🇱🇨',
        is_available: false },
      { name: 'San Cristóbal Y Nieves', phone_prefix: '+1869', flag_emoji: '🇰🇳',
        is_available: false },
      { name: 'San Martín', phone_prefix: '+1', flag_emoji: '🇲🇫',
        is_available: false },
      { name: 'San Pedro Y Miquelón', phone_prefix: '+508', flag_emoji: '🇵🇲',
        is_available: false },
      { name: 'San Vicente Y Las Granadinas', phone_prefix: '+1784',
        flag_emoji: '🇻🇨', is_available: false },
      { name: 'Samoa', phone_prefix: '+685', flag_emoji: '🇼🇸',
        is_available: false },
      { name: 'San Marino', phone_prefix: '+378', flag_emoji: '🇸🇲',
        is_available: false },
      { name: 'Santo Tomé Y Príncipe', phone_prefix: '+239', flag_emoji: '🇸🇹',
        is_available: false },
      { name: 'Arabia Saudí', phone_prefix: '+966', flag_emoji: '🇸🇦',
        is_available: false },
      { name: 'Senegal', phone_prefix: '+221', flag_emoji: '🇸🇳',
        is_available: false },
      { name: 'Serbia', phone_prefix: '+381', flag_emoji: '🇷🇸',
        is_available: false },
      { name: 'Seychelles', phone_prefix: '+248', flag_emoji: '🇸🇨',
        is_available: false },
      { name: 'Sierra Leona', phone_prefix: '+232', flag_emoji: '🇸🇱',
        is_available: false },
      { name: 'Singapur', phone_prefix: '+65', flag_emoji: '🇸🇬',
        is_available: false },
      { name: 'San Martín', phone_prefix: '+721', flag_emoji: '🇲🇫',
        is_available: false },
      { name: 'Islas Salomón', phone_prefix: '+677', flag_emoji: '🇸🇧',
        is_available: false },
      { name: 'Eslovaquia', phone_prefix: '+421', flag_emoji: '🇸🇰',
        is_available: false },
      { name: 'Eslovenia', phone_prefix: '+386', flag_emoji: '🇸🇮',
        is_available: false },
      { name: 'Somalia', phone_prefix: '+252', flag_emoji: '🇸🇴',
        is_available: false },
      { name: 'Sudàfrica', phone_prefix: '+27', flag_emoji: '🇿🇦',
        is_available: false },
      { name: 'Islas Georgia Del Sur Y Sandwich Del Sur', phone_prefix: '+500',
        flag_emoji: '🇬🇸', is_available: false },
      { name: 'Sudán Del Sur', phone_prefix: '+211', flag_emoji: '🇸🇸',
        is_available: false },
      { name: 'España', phone_prefix: '+34', flag_emoji: '🇪🇸',
        is_available: false },
      { name: 'Sri Lanka', phone_prefix: '+94', flag_emoji: '🇱🇰',
        is_available: false },
      { name: 'Svalbard Y Jan Mayen', phone_prefix: '+47', flag_emoji: '🇸🇯',
        is_available: false },
      { name: 'Surinam', phone_prefix: '+597', flag_emoji: '🇸🇷',
        is_available: false },
      { name: 'Suecia', phone_prefix: '+46', flag_emoji: '🇸🇪',
        is_available: false },
      { name: 'Suiza', phone_prefix: '+41', flag_emoji: '🇨🇭',
        is_available: false },
      { name: 'Taiwán', phone_prefix: '+886', flag_emoji: '🇹🇼',
        is_available: false },
      { name: 'Tayikistán', phone_prefix: '+992', flag_emoji: '🇹🇯',
        is_available: false },
      { name: 'Tanzania', phone_prefix: '+255', flag_emoji: '🇹🇿',
        is_available: false },
      { name: 'Tailandia', phone_prefix: '+66', flag_emoji: '🇹🇭',
        is_available: false },
      { name: 'Togo', phone_prefix: '+228', flag_emoji: '🇹🇬',
        is_available: false },
      { name: 'Tokelau', phone_prefix: '+690', flag_emoji: '🇹🇰',
        is_available: false },
      { name: 'Tonga', phone_prefix: '+676', flag_emoji: '🇹🇴',
        is_available: false },
      { name: 'Trinidad Y Tobago', phone_prefix: '+1868', flag_emoji: '🇹🇹',
        is_available: false },
      { name: 'Túnez', phone_prefix: '+216', flag_emoji: '🇹🇳',
        is_available: false },
      { name: 'Turquía', phone_prefix: '+90', flag_emoji: '🇹🇷',
        is_available: false },
      { name: 'Turkmenistán', phone_prefix: '+993', flag_emoji: '🇹🇲',
        is_available: false },
      { name: 'Islas Turcas Y Caicos', phone_prefix: '+1649', flag_emoji: '🇹🇨',
        is_available: false },
      { name: 'Tuvalu', phone_prefix: '+688', flag_emoji: '🇹🇻',
        is_available: false },
      { name: 'Uganda', phone_prefix: '+256', flag_emoji: '🇺🇬',
        is_available: false },
      { name: 'Ucrania', phone_prefix: '+380', flag_emoji: '🇺🇦',
        is_available: false },
      { name: 'Emiratos Árabes Unidos', phone_prefix: '+971', flag_emoji: '🇦🇪',
        is_available: false },
      { name: 'Reino Unido', phone_prefix: '+44', flag_emoji: '🇬🇧',
        is_available: false },
      { name: 'Estados Unidos de América', phone_prefix: '+1', flag_emoji: '🇺🇸',
        is_available: false },
      { name: 'Uruguay', phone_prefix: '+598', flag_emoji: '🇺🇾',
        is_available: false },
      { name: 'Uzbekistán', phone_prefix: '+998', flag_emoji: '🇺🇿',
        is_available: false },
      { name: 'Vanuatu', phone_prefix: '+678', flag_emoji: '🇻🇺',
        is_available: false },
      { name: 'Venezuela', phone_prefix: '+58', flag_emoji: '🇻🇪',
        is_available: false },
      { name: 'Vietnam', phone_prefix: '+84', flag_emoji: '🇻🇳',
        is_available: false },
      { name: 'Wallis Y Futuna', phone_prefix: '+681', flag_emoji: '🇼🇫',
        is_available: false },
      { name: 'Sáhara Occidental', phone_prefix: '+212', flag_emoji: '🇪🇭',
        is_available: false },
      { name: 'Yemen', phone_prefix: '+967', flag_emoji: '🇾🇪',
        is_available: false },
      { name: 'Zambia', phone_prefix: '+260', flag_emoji: '🇿🇲',
        is_available: false },
      { name: 'Zimbabue', phone_prefix: '+263', flag_emoji: '🇿🇼',
        is_available: false }
    ]
    countries.each do |country|
      next if Country.find_by(name: country[:name])

      begin
        puts "Creating country #{country[:name]}"
        Country.create!(country)
      rescue ActiveRecord::RecordInvalid
        puts "The country: #{country[:name]} could not be created!"
      end
    end
  end
end
