on:
  push:
    branches: [ master ]

name: Create release
jobs:
  build:
    name: Create release Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Get Latest merged PRs

    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: | 
        apt update && apt -y upgrade && apt install -y hub
        hub release create -m "TITULO ACTION2" -m "DESCRIPCION ACTION" 11.11.11
